name: Build monorepo on pull requests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  main:
    name: Build sources & run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: use node ${{ env.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - run: make ci
      - run: make lint -j
      - run: make build -j
